on:
  push:
    branches:
      - "master"
name: benchmark

jobs:
  bench:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Check out base
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run criterion benchmarks
        run: cargo bench
        env:
          AOC_SESSION: ${{secrets.AOC_SESSION}}
      # Run iai after criterion to ensure private solutions have been downloaded,
      # since the iai version cannot be built without private inputs.
      - name: Run iai
        run: cargo bench iai --features iai-bench >target/criterion/iai.txt
      - name: Publish results
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/criterion
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    name: deploy pages
    runs-on: ubuntu-latest
    needs: bench
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

