on:
  push:
    branches:
      - "master"
name: benchmark

jobs:
  bench:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Check out base
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run benchmarks
        run: cargo bench
      - name: Publish results
        id: deployment
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: deploy pages
    runs-on: ubuntu-latest
    needs: bench
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

